name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # Triggers the workflow on push to the master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2  # Shallow clone with history

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version to use

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Deploy to GitHub Pages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "jquery404@gmail.com"
        git config --global user.name "jquery404"
        git clone --branch master https://github.com/jquery404/jquery404.github.io.git dist-branch
        cd dist-branch
        find . -mindepth 1 -delete
        cp -R ../jquery404-react/build/* .
        git add .
        git commit -m "Deploy from GitHub Actions"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/jquery404/jquery404.github.io.git master
